export const themesData = [
    {
        id: "dracula",
        icon: "https://duckduckgo.com/i/aab1a4a19dda160a.png",
        description: "Dark theme for GTK",
        link: "https://github.com/dracula/gtk",
        preview: "https://images.pling.com/img/00/00/36/61/48/1687249/big-dracula1.jpg",
    },
    {
        id: "whitesur",
        icon: "nord.svg",
        description: " MacOS like theme for all gtk based desktops.",
        link: "https://github.com/vinceliuice/WhiteSur-gtk-theme",
        preview: "https://images.pling.com/img/00/00/32/24/44/1403328/ef3a77dd79e583851b8d38e4d98fcdf694c6c9d6a22bdda79d52208b0f9d4e553917.png",
    },
    {
        id: "nord",
        icon: "nord.svg",
        description: "Dark Gtk3.20+ theme created using the awesome Nord color pallete. ",
        link: "https://github.com/EliverLara/Nordic",
        preview: "https://raw.githubusercontent.com/EliverLara/Nordic/refs/heads/master/Art/_banner-github.jpg",
    },
    {
        id: "tokoyo",
        icon: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Favetis.gallerycdn.vsassets.io%2Fextensions%2Favetis%2Ftokyo-night%2F1.0.1%2F1642713058241%2FMicrosoft.VisualStudio.Services.Icons.Default&f=1&nofb=1&ipt=a9ddb5bff89a624283dc3cab24d23ab823f479d3ff49e74a6f72ab3e1194460f",
        description: "A GTK theme based on the Tokyo Night colour palette. ",
        link: "https://github.com/Fausto-Korpsvart/Tokyonight-GTK-Theme",
        preview: "https://raw.githubusercontent.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/master/extra/screenshots/Tokyonight.png",
    },
    {
        id: "city",
        icon: "",
        description: "xfce theme",
        link: "https://github.com/linuxthemes/city",
        preview: "https://images.pling.com/img/00/00/11/23/80/1165653/346b8a6a162e1c8115e2577f6712dadb3ae5.png",
    },
    {
        id: "border",
        icon: "",
        description: "border only, no title",
        link: "https://www.pling.com/p/1016214",
        preview: "https://www.pling.com/p/1016214",
    },
    {
        id: "flex",
        icon: "",
        description: "xfce theme",
        link: "https://github.com/sawsedge/fleX",
        preview: "https://images.pling.com/img/00/00/82/73/09/2269263/screenshot-2025-03-07-15-40-55.png",
    },
]

export const iconData = [
    {
        id: "whiteSur",
        icon: "https://raw.githubusercontent.com/vinceliuice/WhiteSur-icon-theme/master/logo.png",
        description: "MacOS Big Sur style icon theme for linux desktops ",
        link: "https://github.com/vinceliuice/WhiteSur-icon-theme",
        preview: "https://raw.githubusercontent.com/vinceliuice/WhiteSur-icon-theme/refs/heads/master/preview.png",
    },
    {
        id: "win10x",
        icon: "",
        description: "A colorful design icon theme for linux desktops ",
        link: "https://github.com/yeyushengfan258/We10X-icon-theme",
        preview: "https://raw.githubusercontent.com/yeyushengfan258/We10X-icon-theme/refs/heads/master/View-1.png",
    },        
    {
        id: "win11x",
        icon: "",
        description: "A colorful design icon theme for linux desktops ",
        link: "https://github.com/yeyushengfan258/Win11-icon-theme",
        preview: "https://raw.githubusercontent.com/yeyushengfan258/Win11-icon-theme/refs/heads/main/View-1.png",
    },
    {
        id: "morewaita",
        icon: "",
        description: "An expanded Adwaita-styled companion icon theme with extra icons for popular apps and MIME types to complement Gnome Shell's original icons. ",
        link: "https://github.com/somepaulo/MoreWaita",
        preview: "https://github.com/somepaulo/MoreWaita?tab=readme-ov-file#apps",
    },
]

export const programData = [
    {
        id: "kde",
        icon: "kde.svg",
        fileArray: [ ".config/plasmarc", ".config/plasmashellrc", ".config/ksplashrc", ".config/konsolerc", ".config/plasma-org.kde.plasma.desktop-appletsrc"],
        description: "KDE Plasma is a graphical shell developed by the KDE community for Unix-like operating systems.",
        homepage: "https://kde.org/plasma-desktop/",
        documentation: "https://docs.kde.org/",
        themes: "",
        issues: "https://bugs.kde.org/index.cgi",
    },
    {
        id: "gnome",
        icon: "gnome.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "GNOME is a free and open-source desktop environment for Linux and other Unix-like operating systems.",
        homepage: "https://www.gnome.org/",
        documentation: "https://developer.gnome.org/documentation/",
        themes: "",
        issues: "https://gitlab.gnome.org/groups/GNOME/-/issues",
    },
    {
        id: "hyprland",
        icon: "hyprland.svg",
        fileArray: [".config/hypr/hyprland.conf", ".config/hypr/hyprlock.conf", ".config/hypr/hyprpaper.conf",],
        description: "Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks.",
        homepage: "https://hypr.land/",
        documentation: "https://wiki.hypr.land/",
        themes: "",
        issues: "https://github.com/hyprwm/Hyprland/issues",
    },
    {
        id: "xfce",
        icon: "xfce.svg",
        fileArray: [".config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml", ".config/xfce4/xfconf/xfce-perchannel-xml/xfce4-terminal.xml", ".config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml", ".config/xfce4/terminal/accels.scm"],
        description: "Xfce is a lightweight desktop environment for UNIX-like operating systems. It aims to be fast and low on system resources, while still being visually appealing and user friendly.",
        homepage: "https://xfce.org/",
        documentation: "https://docs.xfce.org/",
        themes: "",
        issues: "https://gitlab.xfce.org/explore/groups?sort=name_desc",
    },
    {
        id: "micro",
        icon: "micro.svg",
        fileArray: [".config/micro/bindings.json",".config/micro/settings.json"],
        description: "Micro is a modern and intuitive text editor that runs in your terminal. It has features like multiple cursors, syntax highlighting, colorschemes, plugins, and a terminal emulator.",
        homepage: "https://micro-editor.github.io/",
        documentation: "https://micro-editor.github.io/about.html",
        themes: "",
        issues: "https://github.com/zyedidia/micro/issues",
    },
    {
        id: "neovim",
        icon: "neovim.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Neovim is a modern, fast and feature-rich editor that is fully compatible with Vim. It supports plugins, GUIs, LSP, Lua, and more.",
        homepage: "https://neovim.io/",
        documentation: "https://neovim.io/doc/",
        themes: "",
        issues: "https://github.com/neovim/neovim/issues",
    },
    {
        id: "vscode",
        icon: "vscode.svg",
        fileArray: [".config/Code/User/settings.json", ".config/Code/User/keybindings.json"],
        description: "Visual Studio Code is a source-code editor developed by Microsoft for Windows, Linux, macOS and web browsers.",
        homepage: "https://code.visualstudio.com/",
        documentation: "https://code.visualstudio.com/Docs",
        themes: "",
        issues: "https://github.com/microsoft/vscode/issues",
    },
    {
        id: "bash",
        icon: "bash.svg",
        fileArray: [".bashrc"],
        description: "Bash is a free software shell that supports command-line editing, job control, shell functions, arrays, and more. It is compatible with sh and conforms to the POSIX standard.",
        homepage: "https://www.gnu.org/software/bash/",
        documentation: "https://www.gnu.org/software/bash/manual/bash.html",
        themes: "",
        issues: "https://savannah.gnu.org/bugs/?group=bash",
    },
    {
        id: "eza",
        icon: "shell.svg",
        fileArray: [".config/eza/theme.yml"],
        description: "eza is a modern alternative for the venerable file-listing command-line program ls that ships with Unix and Linux operating systems, giving it more features and better defaults.",
        homepage: "https://eza.rocks/",
        documentation: "https://github.com/eza-community/eza",
        themes: "",
        issues: "https://github.com/eza-community/eza/issues",
    },
    {
        id: "ghostty",
        icon: "ghostty.png",
        fileArray: [".config/ghostty/config"],
        description: "Ghostty is a fast, feature-rich, and cross-platform terminal emulator that uses platform-native UI and GPU acceleration.",
        homepage: "https://ghostty.org/",
        documentation: "https://ghostty.org/docs",
        themes: "",
        issues: "https://github.com/ghostty-org/ghostty/issues",
    },
    {
        id: "kitty",
        icon: "shell.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "kitty is a fast, feature-rich, and cross-platform terminal emulator that uses GPU and SIMD vector CPU instructions for best performance. It supports graphics, ligatures, hyperlinks, scripting, kittens, and more.",
        homepage: "https://sw.kovidgoyal.net/kitty/",
        documentation: "https://sw.kovidgoyal.net/kitty/overview/",
        themes: "",
        issues: "https://github.com/kovidgoyal/kitty/issues",
    },
    {
        id: "alacritty",
        icon: "shell.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Alacritty is a modern terminal emulator that integrates with other applications and allows for extensive configuration.",
        homepage: "https://alacritty.org/",
        documentation: "https://alacritty.org/config-alacritty.html",
        themes: "",
        issues: "https://github.com/alacritty/alacritty/issues",
    },
]