export const themesData = [
    {
        id: "city",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "border",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "fleX",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "adwaita",
        icon: "",
        description: "",
        link: "",
    },
]

export const iconData = [
    {
        id: "winSur",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "macOs",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "win10x",
        icon: "",
        description: "",
        link: "",
    },        {
        id: "win11x",
        icon: "",
        description: "",
        link: "",
    },
    {
        id: "morewaita",
        icon: "",
        description: "",
        link: "",
    },
]

export const programData = [
    {
        id: "kde",
        icon: "kde.svg",
        fileArray: ["CONTRIBUTING.md",],
        description: "KDE Plasma is a graphical shell developed by the KDE community for Unix-like operating systems.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "gnome",
        icon: "gnome.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "GNOME is a free and open-source desktop environment for Linux and other Unix-like operating systems.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "hyprland",
        icon: "hyprland.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "xfce",
        icon: "xfce.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Xfce is a lightweight desktop environment for UNIX-like operating systems. It aims to be fast and low on system resources, while still being visually appealing and user friendly.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "micro",
        icon: "micro.svg",
        fileArray: [".config/micro/settings.json"],
        description: "Micro is a modern and intuitive text editor that runs in your terminal. It has features like multiple cursors, syntax highlighting, colorschemes, plugins, and a terminal emulator.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "neovim",
        icon: "neovim.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Neovim is a modern, fast and feature-rich editor that is fully compatible with Vim. It supports plugins, GUIs, LSP, Lua, and more.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "vscode",
        icon: "vscode.svg",
        fileArray: [".config/Code/User/settings.json", ".config/Code/User/keybindings.json"],
        description: "Visual Studio Code is a source-code editor developed by Microsoft for Windows, Linux, macOS and web browsers.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "bash",
        icon: "bash.svg",
        fileArray: [".bashrc"],
        description: "Bash is a free software shell that supports command-line editing, job control, shell functions, arrays, and more. It is compatible with sh and conforms to the POSIX standard.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "eza",
        icon: "shell.svg",
        fileArray: [".config/eza/theme.yml"],
        description: "eza is a modern alternative for the venerable file-listing command-line program ls that ships with Unix and Linux operating systems, giving it more features and better defaults.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "ghostty",
        icon: "ghostty.png",
        fileArray: [".config/ghostty/config"],
        description: "Ghostty is a fast, feature-rich, and cross-platform terminal emulator that uses platform-native UI and GPU acceleration.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "kitty",
        icon: "shell.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "kitty is a fast, feature-rich, and cross-platform terminal emulator that uses GPU and SIMD vector CPU instructions for best performance. It supports graphics, ligatures, hyperlinks, scripting, kittens, and more.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
    {
        id: "alacritty",
        icon: "shell.svg",
        fileArray: ["CONTRIBUTING.md"],
        description: "Alacritty is a modern terminal emulator that integrates with other applications and allows for extensive configuration.",
        homepage: "",
        documentation: "",
        themes: "",
        issues: "",
    },
]